version: 2
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Set version
          command: |
            export SALEOR_VERSION=$(git rev-parse --short HEAD)
            if [ -n "$CIRCLE_TAG" ]; then
              export SALEOR_VERSION=$(git describe --tags)
            fi
            sed -i.bak "s#'dev'#'$SALEOR_VERSION'#" saleor/__init__.py
      - run:
          name: Build application Docker image
          command: |
            docker build \
              --build-arg STATIC_URL=$STATIC_URL \
              -t ablazleon/smallshop:latest .
      - run:
          name: Run tests
          command: |
            docker run -d --name db -e POSTGRES_USER=saleor -e POSTGRES_PASSWORD=saleor postgres:12.2-alpine
            docker run --network container:db --rm -e DATABASE_URL mirumee/saleor:latest pytest
          environment:
            DATABASE_URL: postgres://saleor:saleor@localhost:5432/saleor
      - deploy:
          name: Push Docker image
          command: |
            docker login -u $DOCKERCLOUD_USER -p $DOCKERCLOUD_PASS
            docker tag ablazleon/smallshop:latest ablazleon/smallshop:$CIRCLE_SHA1
            docker push ablazleon/smallshop:$CIRCLE_SHA1
            docker push ablazleon/smallshop:latest
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GCLOUD_SERVICE_KEY
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/build-image:
          dockerfile: Dockerfile
          google-project-id: GOOGLE_PROJECT_ID
          image: $IMAGE_NAME
          registry-url: "gcr.io"
          tag: $CIRCLE_SHA1
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          image: $IMAGE_NAME
          registry-url: "gcr.io"
          tag: $CIRCLE_SHA1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /demo.*/
